// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetUmbracoClientdrawerApiV1GetdataData, GetUmbracoClientdrawerApiV1GetdataErrors, GetUmbracoClientdrawerApiV1GetdataResponses, GetUmbracoClientdrawerApiV1GetheaderactiondataData, GetUmbracoClientdrawerApiV1GetheaderactiondataErrors, GetUmbracoClientdrawerApiV1GetheaderactiondataResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class V1Service {
    public static getUmbracoClientdrawerApiV1Getdata<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoClientdrawerApiV1GetdataData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoClientdrawerApiV1GetdataResponses, GetUmbracoClientdrawerApiV1GetdataErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/clientdrawer/api/v1/getdata',
            ...options
        });
    }
    
    public static getUmbracoClientdrawerApiV1Getheaderactiondata<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoClientdrawerApiV1GetheaderactiondataData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoClientdrawerApiV1GetheaderactiondataResponses, GetUmbracoClientdrawerApiV1GetheaderactiondataErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/clientdrawer/api/v1/getheaderactiondata',
            ...options
        });
    }
}
