// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44315' | (string & {});
};

export type AssemblyModel = {
    name?: string | null;
    version?: string | null;
};

export type Change = {
    text: string;
    link?: string | null;
};

export type DataModel = {
    heading: string;
    primaryAssembly?: AssemblyModel | null;
    environments?: Array<EnvironmentModel> | null;
    changeLog: Array<LogEntry>;
    systemInformation: SystemInformationModel;
};

export type EnvironmentModel = {
    name: string;
    primaryUrl: string;
    umbracoUrl: string;
    disableUmbracoUrl: boolean;
    isCurrent: boolean;
    iconClass: string;
};

export type HeaderActionModel = {
    clientName: string;
    iconClass: string;
    iconImageFilePath?: string | null;
    iconSVG?: string | null;
    headerButtonMode: string;
    currentEnvironmentName?: string | null;
};

export type LogEntry = {
    date: string;
    changes?: Array<Change> | null;
    readonly formattedDate: string;
    readonly friendlyDatePeriod: string;
};

export type SystemInformationModel = {
    enabled: boolean;
    assemblies: Array<AssemblyModel>;
};

export type LogEntryWritable = {
    date: string;
    changes?: Array<Change> | null;
};

export type GetUmbracoClientdrawerApiV1GetdataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/clientdrawer/api/v1/getdata';
};

export type GetUmbracoClientdrawerApiV1GetdataErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUmbracoClientdrawerApiV1GetdataResponses = {
    /**
     * OK
     */
    200: DataModel;
};

export type GetUmbracoClientdrawerApiV1GetdataResponse = GetUmbracoClientdrawerApiV1GetdataResponses[keyof GetUmbracoClientdrawerApiV1GetdataResponses];

export type GetUmbracoClientdrawerApiV1GetheaderactiondataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/clientdrawer/api/v1/getheaderactiondata';
};

export type GetUmbracoClientdrawerApiV1GetheaderactiondataErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUmbracoClientdrawerApiV1GetheaderactiondataResponses = {
    /**
     * OK
     */
    200: HeaderActionModel;
};

export type GetUmbracoClientdrawerApiV1GetheaderactiondataResponse = GetUmbracoClientdrawerApiV1GetheaderactiondataResponses[keyof GetUmbracoClientdrawerApiV1GetheaderactiondataResponses];
